### PR TITLE
include example ECP5 architecture syntax

### PR DESCRIPTION
**Pull request by gojimmypi**
for "_Ensure to include the ECP5 architecture when building nextpnr_" in the docs

### CODE REVIEW

**Comment by gojimmypi** [comment]
I performed an in-browser edit without fork. Is there an easy way for me to address this:

image

**Comment by smunaut** [comment]
Huh I think TRELLIS_ROOT doesn't exist in newer nextpnr, it's TRELLIS_PREFIX now (and doesn't include the /share/trellis part either)

**Comment by gojimmypi** [comment]
@smunaut well, that might be true also. I've not built a fresh `prjtrellis` in some time, I see:

```
-- Configuring architecture : ecp5
-- TRELLIS_INSTALL_PREFIX not defined using -DTRELLIS_INSTALL_PREFIX=/path-prefix/to/prjtrellis-installation. Default to /usr/local or reset by -DCMAKE_INSTALL_PREFIX when building prjtrellis/libtrellis
```
which may be related to my other error:

```
[ 37%] Built target bbasm
[ 38%] Generating ecp5/chipdbs/chipdb-25k.bba
Traceback (most recent call last):
  File "/home/gojimmypi/workspace/nextpnr/ecp5/trellis_import.py", line 3, in <module>
    import database
ModuleNotFoundError: No module named 'database'
make[2]: *** [ecp5/chipdbs/chipdb-25k.bba] Error 1
```
that I hoped would be resolved with `export PYTHONPATH="~/workspace/prjtrellis/database"` (but wasn't) so I never even make it as far as building `nextpnr`.

**Comment by smunaut** [comment]
I actually opened https://github.com/YosysHQ/nextpnr/pull/404  earlier today which searches in the install prefix rather than the hardcoded /usr/local  that might be useful for you.

**Comment by gojimmypi** [comment]
ah yes, thank you. I'll check that out. 

indeed you are correct regarding `nextpnr` change to `-DTRELLIS_INSTALL_PREFIX` as noted [here](https://github.com/YosysHQ/nextpnr#nextpnr-ecp5)

**Comment by gojimmypi** [comment]
ah. thanks. so [this](https://github.com/YosysHQ/nextpnr#nextpnr-ecp5) is wrong, too?

image

`/path/to/prjtrellis` should be just `/usr` at install time?

**Comment by smunaut** [comment]
Well it the path to where you installed prjtrellis.  (i.e. what you used as the `CMAKE_INSTALL_PREFIX` when doing the cmake of prjtrellis), so it's really how you define `/path/to/prjtrellis` ....

**Comment by gojimmypi** [comment]
Does the binary end up in `/usr/bin` for `sudo make install` in this example:

```
cmake -DARCH=ecp5 -DTRELLIS_INSTALL_PREFIX=/usr
make -j$(nproc)
sudo make install
```

**Comment by smunaut** [comment]
Well no. The `TRELLIS_INSTALL_PREFIX` is where it looks for prjtrellis.
That's not where things are going to get installed.
You also need to set `CMAKE_INSTALL_PREFIX` if you want the binaries in `/usr`

**Comment by gojimmypi** [comment]
ok. thanks. let's see if I can resolve my `No module named 'database'` problem and I'll give it a try.

**Comment by smunaut** [comment]
@daveshah1 huh ... that example was wrong, see my comment ...

**Comment by daveshah1** [comment]
Oops, missed that

**Comment by gojimmypi** [comment]
sorry for all the newbie hassles here. thanks for the correction @daveshah1 and for info @smunaut

**Pull request merged**
