### PR TITLE
Change theme to Sphinx Material Design

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Robert Winkler <rwinkler@antmicro.com>

### CODE REVIEW

**Comment by mithro** [comment]
Example output can be found at https://mithro-prjtrellis.readthedocs.io/en/latest/

**Comment by gsomlo** [comment]
I'm packaging prjtrellis for Fedora, and just noticed that this commit "unbundled" the "markdown_code_symlinks" module (which used to be included under docs/ in the prjtrellis source tree. This breaks the ability to build documentation from within an RPM builder (which can't "side-load" python modules that aren't themselves available as packaged RPMs).
Is there a way to build (any shape or form of) the docs without installing markdown_code_symlinks, since I'd rather not recurse into becoming the Fedora maintainer of yet-another-python-module? :)
Thanks for any ideas!

**Comment by mithro** [comment]
@gsomlo You should note that the removed version is actually very different to the python module version.

**Comment by rrika** [comment]
The new docs are blank when viewed without javascript :(

**Pull request merged**
