### PR TITLE
Bitstream decompression and better handling of crc & dummies (so they also work with MachXO2)

### PR DESCRIPTION
**Pull request by AndresNavarro82**
MachXO2 support helped by some earlier work by cr1901 in figuring
out some bitstream differences (row/column swapped, 1 based indexing
for columns, frame order reversed, etc) and writing the first fuzzers

Signed-off-by: Andres Navarro <canavarro82@gmail.com>

### CODE REVIEW

**Comment by cr1901** [comment]
@daveshah1 I'm fine w/ the bitstream compression stuff being merged upstream, since it applies to both ECP5 and MachXO2. I can always merge it back into my branch.

@AndresNavarro82 Is there any possibility you could just extract the compression-specific commits for this PR?

**Comment by AndresNavarro82** [comment]
Sure, let me try to do that

**Comment by AndresNavarro82** [comment]
Ok, I think this is good to go now

**Comment by anuejn** [comment]
Is there any hope, that MachXO2 support will be merged into prjtrellis too?

**Comment by AndresNavarro82** [comment]
MachXO2 support is still a little green (but moving fast!).  We are working with @cr1901 in [this branch](https://github.com/cr1901/prjtrellis/tree/facade)
I should be updated soon to bring it back up to date with recent upstream changes
We are ironing out some normalization issues and there's still some work to be done in the IO blocks but we hope to have something simple working in the near term.
As for merging into prjtrellis that would be the ideal, but I feel the code should be more stable/mature for that.  No need to rush it.

**Pull request merged**
